### ISSUE TITLE
Non-Linux versions

### ISSUE THREAD

**Issue by obonaventure** [multipath-tcp/mptcp-vagrant#1]
It would be nice to have support for Macos in the up.sh script or at least check that the script is running under Linux before trying to configure iptables

**Comment by rmoriz** [comment]
:+1:

**Comment by mpyw** [comment]
<del>I forked into [here] and [modified].</del>

&#20;<ins>Deleted after this issue closed. thx :D</ins>

Masquerading itself seems to work well, however, the specified version of Ubuntu kernel does not support MPTCP in the first place... wtf..
![2015-09-15 16 15 36](https://cloud.githubusercontent.com/assets/1351893/9870602/5c63a4f4-5bc8-11e5-8693-eaeb2bae0ebb.png)
![2015-09-15 16 26 32](https://cloud.githubusercontent.com/assets/1351893/9870605/5f6d3d36-5bc8-11e5-8d4e-b2f1f302ada6.png)

**Comment by mpyw** [comment]
Sorry, `vagrant reload` leads to work! xD

![2015-09-15 16 52 51](https://cloud.githubusercontent.com/assets/1351893/9870840/64a582a2-5bca-11e5-9704-02d31f5023aa.png)

**Comment by rbauduin** [comment]
Cool! I will switch to vagrant triggers too, and then a script can do host OS detection and execute the required instructions.

**Comment by mpyw** [comment]
:+1:

**Comment by rbauduin** [comment]
Actually I already had a vagrant-triggers version which I abandoned due to problems at the time. With vagrant-triggers 0.5.2 it works fine though. I integrated the pfctl rules, can you try it with the repo https://github.com/rbauduin/vagrant_mptcp ?

**Comment by mpyw** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: 

![2015-09-15 18 55 14](https://cloud.githubusercontent.com/assets/1351893/9873523/659c5616-5bdb-11e5-8363-40150a198a8e.png)

**Comment by rbauduin** [comment]
Updated master branch with code from rbauduin/vagrant_mptcp (forced push) including OS X NAT. Previous version still in branch "kernel-dev".
