### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by obonaventure** [multipath-tcp/mptcp-vagrant#3]
Does not work anymore on MacOS

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'rbauduin/mptcp-minimal' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default: 
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
    default: Running: /var/folders/y2/6bhc7q71631336m7yz_bzfs80000gn/T/vagrant-shell20151124-30332-16orpty.sh
==> default: stdin: is not a tty
==> default: + host_ipv4=192.168.33.1
==> default: + ip route del default via 10.0.2.2
==> default: + ip route add default via 192.168.33.1
==> default: Running triggers after up...
==> default: Executing command "./scripts/post_up.sh"...
==> default: port up nat
==> default: + echo 'port up nat'
==> default: ++ uname
==> default: + uname_str=Darwin
==> default: + echo '==> Enabling IP Masquerading'
==> default: ==> Enabling IP Masquerading
==> default: + [[ Darwin == \L\i\n\u\x ]]
==> default: + [[ Darwin == \D\a\r\w\i\n ]]
==> default: + echo 'nat on en0 from 192.168.33.0/24 to any -> en0'
==> default: + sudo pfctl -ef -
==> default: Command execution finished.
The command "./scripts/post_up.sh" returned a failed exit code. The
error output is shown below:
- echo 'port up nat'
  ++ uname
- uname_str=Darwin
- echo '==> Enabling IP Masquerading'
- [[ Darwin == \L\i\n\u\x ]]
- [[ Darwin == \D\a\r\w\i\n ]]
- echo 'nat on en0 from 192.168.33.0/24 to any -> en0'
- sudo pfctl -ef -

**Comment by obonaventure** [comment]
script should ask which interface is used for NAT. In my case, Ethernet is on en3 and Wifi on en0

**Comment by rbauduin** [comment]
From the BNF at https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man5/pf.conf.5.html the next command should be valid: 
`echo "nat from 192.168.33.0/24" | sudo pfctl -ef -`.
Can you check if this is accepted and works?

**Comment by cpaasch** [comment]
I have the same issue. `echo "nat from 192.168.33.0/24" | sudo pfctl -ef -` does not fixes it for me :(

**Comment by ginoledesma** [comment]
Most likely certain OS X configs don't have IP Forwarding enabled. This fixed it for me: 

```
sudo sysctl net.net.ip.forwarding=1
```

**Comment by dur3x** [comment]
I can confirm that the solution for OSX is to enable the IP forwarding by this command 
`sudo sysctl net.inet.ip.forwarding=1`

**Comment by cpaasch** [comment]
Fixed with https://github.com/multipath-tcp/mptcp-vagrant/pull/4.
